apiVersion: apps/v1
kind: Deployment
metadata:
  name: myaq-frontend-deployment
  labels:
    app: nginx-angular
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-angular
  template:
    metadata:
      labels:
        app: nginx-angular
    spec:
      containers:
      - name: myaq-frontend-container
        image: index.docker.io/rpanops/myaq-frontend:1.0.0
        ports:
        - containerPort: 80
        resources: {}
 
---
apiVersion: v1
kind: Service
metadata:
  name: myaq-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: nginx-angular
  ports:
  - protocol: TCP
    port: 80
