apiVersion: apps/v1
kind: Deployment
metadata:
  name: myaq-backend-deployment
  labels:
    app: spring-boot-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-microservice
  template:
    metadata:
      labels:
        app: spring-boot-microservice
    spec:
      containers:
      - name: myaq-backend-container
        image: index.docker.io/rpanops/myaq-backend:1.0.0
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "1Gi" #1GB
            cpu: "200m" #200 millicpu (.2 cpu or 20% of the cpu)
---
apiVersion: v1
kind: Service
metadata:
  name: myaq-backend-service
spec:
  type: LoadBalancer
  selector:
    app: spring-boot-microservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080