apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: myaq-cluster
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: t3.small
    desiredCapacity: 2
  - name: ng-2
    instanceType: t3.small
    desiredCapacity: 2